SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `birthright`.`equipment` DROP COLUMN `intervalConf` , DROP COLUMN `conference` , DROP COLUMN `user_id` , DROP COLUMN `discrepancy` , DROP COLUMN `room` , DROP COLUMN `section_id` , DROP COLUMN `organization_id` , ADD COLUMN `quantity` INT(11) NOT NULL  AFTER `sendRegister` , CHANGE COLUMN `sendRegister` `sendRegister` DATETIME NULL DEFAULT NULL  AFTER `alias` , CHANGE COLUMN `includeRegister` `includeRegister` DATETIME NULL DEFAULT NULL  AFTER `quantity` , CHANGE COLUMN `description` `description` VARCHAR(255) NOT NULL  ;

CREATE  TABLE IF NOT EXISTS `birthright`.`patrimonies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `equipment_id` INT(11) NULL DEFAULT NULL ,
  `organization_id` INT(11) NULL DEFAULT NULL ,
  `section_id` INT(11) NULL DEFAULT NULL ,
  `room` VARCHAR(20) NOT NULL ,
  `discrepancy` VARCHAR(150) NULL DEFAULT NULL ,
  `user_id` INT(11) NULL DEFAULT NULL ,
  `conference` DATETIME NULL DEFAULT NULL ,
  `orderNum` INT(11) NULL DEFAULT NULL ,
  `intervalConf` INT(11) NULL DEFAULT NULL ,
  `created` DATETIME NULL DEFAULT NULL ,
  `modified` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
